version: "3.9"
services:
  # heroku-starter-golang:
  #   build: .
  #   environment:
  #     - ENV=production
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=password
  #     - DB_NAME=postgres
  #     - DB_HOST=postgres
  #     - SSL_MODE=disable
  #   ports:
  #     - 5001:5001
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
